name: End-to-end tests
on:
  push:
    branches: none
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
#on: [push]
#on:
#  pull_request:
#    types: [opened, reopened]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: cypress
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/cypress/videos
      - run: ls . -la
      - run: ls cypress -la
      - run: ls cypress/cypress -la
