name: docke-test-nobuild
on:
  push:
    branches: none
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-container:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        run: |
          ls -la
          docker run -d -it --name testdocker -p 5010:80 tiangolo/uwsgi-nginx-flask:python3.8

      #Dockerfile build
      #- uses: docker/build-push-action@v2
      #  with:
      #    file: Dockerfile
      #    tags: testdoocker
      #    push: false # pushしない      
      #docker run
      #- uses: addnab/docker-run-action@v3
      #  with:
      #    image: tiangolo/uwsgi-nginx-flask:python3.8
      #    #run: ls -la
      - run: |
          ls -la
          docker ps -a

