name: caddie_container
on: [push]
#on:
#  pull_request:
#    types: [opened, reopened]
#    path:
#      - 'model.py'

jobs:
  caddie-docker:
    runs-on: ubuntu-latest
    container: #起動するコンテナイメージを指定
      image: gamasenninn/scaddie #指定のdockerイメージを使用
    steps: #dockerコンテナ内でステップを実行
      - uses: actions/checkout@v2
      - name: caddie unittest
        run: |
          cd /app
          ls -la 
